<?php

namespace pspiess\LetsplayBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceRepository extends EntityRepository {

    public function getNextInviceNumber() {
        $arrInvice = $this->getEntityManager()
            ->createQuery(
                'SELECT MAX(i.invoiceNumber)  + 1 AS NEXTINVOICENUMBER FROM pspiessLetsplayBundle:Invoice i'
            )
            ->getResult();
        
        return $arrInvice[0]['NEXTINVOICENUMBER'];
    }

}
