<?php

namespace pspiess\LetsplayBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PayofficeposRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayofficeposRepository extends EntityRepository
{
    
        public function getPayofficepos() {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
                ->select('p', 'i')
                ->from('pspiessLetsplayBundle:Payoffice', 'p')
                ->leftJoin('p.invoice_id', 'i');
        try {
            return $query->getQuery()->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    
}
