pspiess_letsplay_customer:
    pattern:  /admin/customer
    defaults: { _controller: pspiessLetsplayBundle:Customer:index }
    
pspiess_letsplay_customer_new:
    pattern:  /admin/customer/new
    defaults: { _controller: pspiessLetsplayBundle:Customer:new }
    
pspiess_letsplay_customer_create:
    pattern:  /admin/customer/create
    defaults: { _controller: pspiessLetsplayBundle:Customer:create }
    
pspiess_letsplay_customer_edit:
    pattern:  /admin/customer/edit/{id}
    defaults: { _controller: pspiessLetsplayBundle:Customer:edit }
    
pspiess_letsplay_customer_update:
    pattern:  /admin/customer/update/{id}
    defaults: { _controller: pspiessLetsplayBundle:Customer:update }
   

pspiess_letsplay_customer_delete:
    pattern:  /admin/customer/delete/{id}
    defaults: { _controller: pspiessLetsplayBundle:Customer:delete }