pspiess_letsplay_invoice:
    pattern:  /admin/invoice
    defaults: { _controller: pspiessLetsplayBundle:Invoice:index }
    
pspiess_letsplay_invoice_new:
    pattern:  /admin/invoice/new/{id}
    defaults: { _controller: pspiessLetsplayBundle:Invoice:new, id:0}
    options:
        expose: true
pspiess_letsplay_invoice_create:
    pattern:  /admin/invoice/create
    defaults: { _controller: pspiessLetsplayBundle:Invoice:create }

pspiess_letsplay_invoice_edit:
    pattern:  /admin/invoice/edit/{id}
    defaults: { _controller: pspiessLetsplayBundle:Invoice:edit }
    
pspiess_letsplay_invoice_show:
    pattern:  /admin/invoice/show/{id}
    defaults: { _controller: pspiessLetsplayBundle:Invoice:show }
    
pspiess_letsplay_invoice_update:
    pattern:  /admin/invoice/update/{id}
    defaults: { _controller: pspiessLetsplayBundle:Invoice:update }