pspiess_letsplay:
    pattern:  /admin/
    defaults: { _controller: pspiessLetsplayBundle:Default:index }

pspiess_letsplay_projects:
    pattern:  /admin/projects
    defaults: { _controller: pspiessLetsplayBundle:Default:projects }

pspiess_letsplay_projects_add:
    pattern:  /admin/projects/add
    defaults: { _controller: pspiessLetsplayBundle:Default:addProject }

pspiess_letsplay_employees:
    pattern:  /admin/employees
    defaults: { _controller: pspiessLetsplayBundle:Default:employees }

pspiess_letsplay_employees_add:
    pattern:  /admin/employees/add
    defaults: { _controller: pspiessLetsplayBundle:Default:addEmployee }

pspiess_letsplay_profile:
    pattern:  /admin/profile
    defaults: { _controller: pspiessLetsplayBundle:Default:profile }