pspiess_letsplay_customer:
    resource: "@pspiessLetsplayBundle/Controller/"
    resource: "@pspiessLetsplayBundle/Resources/config/customer.yml"
    prefix:   /
    
pspiess_letsplay_price:
    resource: "@pspiessLetsplayBundle/Controller/"
    resource: "@pspiessLetsplayBundle/Resources/config/price.yml"
    prefix:   /
    
pspiess_letsplay_field:
    resource: "@pspiessLetsplayBundle/Controller/"
    resource: "@pspiessLetsplayBundle/Resources/config/field.yml"
    prefix:   /
    
pspiess_letsplay:
    pattern:  /admin/
    defaults: { _controller: pspiessLetsplayBundle:Default:index }
    
pspiess_letsplay_profile:
    pattern:  /admin/profile
    defaults: { _controller: pspiessLetsplayBundle:Default:profile }