pspiess_letsplay:
    pattern:  /admin/
    defaults: { _controller: pspiessLetsplayBundle:Default:index }

pspiess_letsplay_projects:
    pattern:  /admin/projects
    defaults: { _controller: pspiessLetsplayBundle:Default:projects }

pspiess_letsplay_projects_add:
    pattern:  /admin/projects/add
    defaults: { _controller: pspiessLetsplayBundle:Default:addProject }

pspiess_letsplay_employees:
    pattern:  /admin/employees
    defaults: { _controller: pspiessLetsplayBundle:Default:employees }

pspiess_letsplay_employees_add:
    pattern:  /admin/employees/add
    defaults: { _controller: pspiessLetsplayBundle:Default:addEmployee }
    
pspiess_letsplay_price1:
    pattern:  /admin/price1
    defaults: { _controller: pspiessLetsplayBundle:Default:price }
    
pspiess_letsplay_price:
    pattern:  /admin/price
    defaults: { _controller: pspiessLetsplayBundle:Price:index }
    
pspiess_letsplay_price_show:
    pattern:  /admin/price/show/{id}
    defaults: { _controller: pspiessLetsplayBundle:Price:show }
    
pspiess_letsplay_price_edit:
    pattern:  /admin/price/edit/{id}
    defaults: { _controller: pspiessLetsplayBundle:Price:edit }
    
pspiess_letsplay_price_delete:
    pattern:  /admin/price/delete/{id}
    defaults: { _controller: pspiessLetsplayBundle:Price:delete }

pspiess_letsplay_price_add:
    pattern:  /admin/price/add
    defaults: { _controller: pspiessLetsplayBundle:Default:addPrice }

pspiess_letsplay_profile:
    pattern:  /admin/profile
    defaults: { _controller: pspiessLetsplayBundle:Default:profile }