services:
    pspiess.letsplay.menu.voter.request:
        class: pspiess\LetsplayBundle\Menu\RequestVoter
        arguments:
            - @service_container
        tags:
            - { name: knp_menu.voter }
            
    pspiess.letsplay.menu.builder:
        class:  pspiess\LetsplayBundle\Menu\MenuBuilder
        arguments:
            - '@doctrine.orm.entity_manager'
