#pspiess_letsplay:
#    resource: "@pspiessLetsplayBundle/Controller/"
#    type:     annotation
#    prefix:   /
    
pspiess_letsplay:
    resource: "@pspiessLetsplayBundle/Controller/"
    resource: "@pspiessLetsplayBundle/Resources/config/routing.yml"
    prefix:   /
    
#biberltd_currency:
#    resource: "@VendorNameSampleBundle/Resources/config/routing.yml"
#    prefix:   /
#    
#customer:
#    resource: "@pspiessLetsplayBundle/Controller/"
#    type:     annotation
#    prefix:   /customerd

#_user_bundle:
#    resource: "@UserBundle/Resources/config/routing.yml"

#fos_js_routing:
#    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"