<?php

namespace pspiess\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubcategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubcategoryRepository extends EntityRepository {

    /**
     * @param string search for description
     * 
     * @return array with Subcategory entities
     * 
     */
    public function GetSubcategoryByName($sKeyword = '', $iMaincategory = null) {
        $query = $this->createQueryBuilder('s');
        if ($sKeyword) {
            $query->where($this->createQueryBuilder('s')->expr()->like('s.description', ':keyword'))
                    ->setParameter('keyword', '%' . $sKeyword . '%');
        }

        if ($iMaincategory) {
            $query->andWhere('s.maincategory = :maincategory')
                    ->setParameter('maincategory', $iMaincategory);
        }

        return $query->getQuery()->getResult();
    }

}
